name: Daily Fund Price Scraper

on:
  schedule:
    - cron: '1 21 * * *'  # Runs daily at 22:00 UTC (5pm EST, 6pm EDT)
  workflow_dispatch:     # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scrape_fund_price.py

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Set up authentication for pushing
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push results
        run: |
          git add -f data/*.csv data/*.price
          git commit -m "Update fund prices" || echo "No changes to commit"
          git push
